### ISSUE TITLE
hide left and right arrows on carousel when only one slide is present

### ISSUE THREAD

**Issue by russdanner** [craftersoftware/craftersoftware-blueprint#10]
<img width="1250" alt="screen shot 2018-01-18 at 12 00 49 am" src="https://user-images.githubusercontent.com/169432/35081545-d6b3abe8-fbe2-11e7-9ced-167af2a6d2ff.png">

**Comment by jvega-crafter** [comment]
https://github.com/craftersoftware/craftersoftware-blueprint/pull/13
