### ISSUE TITLE
Add a (x) style close button to the contact form

### ISSUE THREAD

**Issue by russdanner** [craftersoftware/craftersoftware-blueprint#14]
The hubspot form does not redirect the user (because this dialog is available everywhere) 

The user needs a way to close the dialog that makes sense with the user interaction.  I think an X button in the upper right is the best option for now.

<img width="1383" alt="screen shot 2018-01-19 at 10 54 39 am" src="https://user-images.githubusercontent.com/169432/35159241-91900a54-fd07-11e7-96f5-fbeb9fd947a9.png">

**Comment by jvega-crafter** [comment]
https://github.com/craftersoftware/craftersoftware-blueprint/pull/15
