### ISSUE TITLE
Hamburger menu (top navigation) does not work on some mobile phones

### ISSUE THREAD

**Issue by russdanner** [craftersoftware/craftersoftware-blueprint#16]
User is not able to click on menu items via mobile responsive view on some phones

Android phone does not work

Iphone 8 does work

**Comment by sumerjabri** [comment]
Broken on Android 8: Chrome and Firefox

**Comment by jvega-crafter** [comment]
https://github.com/craftersoftware/craftersoftware-blueprint/pull/20

**Comment by russdanner** [comment]
verified
