### ISSUE TITLE
Replace gear image in the footer of every page

### ISSUE THREAD

**Issue by louloujames** [craftersoftware/craftersoftware-blueprint#19]
![gear-image](https://user-images.githubusercontent.com/15113775/35286110-1305707e-002d-11e8-8a5f-ecb7a5b6d1ae.PNG)

I'm putting this in to track and downloading a new image to use and will update the ticket.

**Comment by louloujames** [comment]
Can you replace the gear image in the footer of the new crafter software website to the attached image in this ticket?
![gears-image-craftersoftware-website](https://user-images.githubusercontent.com/15113775/35300152-a410107e-0055-11e8-91e0-384f3e09b7a5.jpg)

**Comment by russdanner** [comment]
This issue can be closed.
